Version R 2.20c
2025-08-31 10:45:40.095136
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/LucasR.py", line 20, in <module>
    Code.Base.Init.init()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Base/Init.py", line 18, in init
    resp = LucasChessGui.run_gui(main_procesador)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/LucasChessGui.py", line 133, in run_gui
    procesador.iniciar_gui()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 184, in iniciar_gui
    self.main_window = MainWindow.MainWindow(self)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/MainWindow.py", line 25, in __init__
    LCDialog.LCDialog.__init__(self, owner, titulo, icono, extparam)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/QT/LCDialog.py", line 15, in __init__
    self.setWindowFlags(
TypeError: 'PySide2.QtCore.Qt.WindowType' object cannot be interpreted as an integer
TypeError: 'PySide2.QtCore.Qt.WindowType' object cannot be interpreted as an integer

The above exception was the direct cause of the following exception:

2025-08-31 10:46:08.623126
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/LucasR.py", line 20, in <module>
    Code.Base.Init.init()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Base/Init.py", line 18, in init
    resp = LucasChessGui.run_gui(main_procesador)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/LucasChessGui.py", line 133, in run_gui
    procesador.iniciar_gui()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 184, in iniciar_gui
    self.main_window = MainWindow.MainWindow(self)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/MainWindow.py", line 25, in __init__
    LCDialog.LCDialog.__init__(self, owner, titulo, icono, extparam)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/QT/LCDialog.py", line 16, in __init__
    QtCore.Qt.Dialog
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/QT/QtMacCompat.py", line 32, in safe_or
    return orig_or(self, other)
           ^^^^^^^^^^^^^^^^^^^^
SystemError: <slot wrapper '__or__' of 'PySide2.QtCore.Qt.WindowType' objects> returned a result with an exception set
2025-08-31 10:46:24.261620
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/LucasR.py", line 20, in <module>
    Code.Base.Init.init()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Base/Init.py", line 18, in init
    resp = LucasChessGui.run_gui(main_procesador)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/LucasChessGui.py", line 133, in run_gui
    procesador.iniciar_gui()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 184, in iniciar_gui
    self.main_window = MainWindow.MainWindow(self)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/MainWindow.py", line 25, in __init__
    LCDialog.LCDialog.__init__(self, owner, titulo, icono, extparam)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/QT/LCDialog.py", line 15, in __init__
    self.setWindowFlags(
TypeError: 'PySide2.QtWidgets.QWidget.setWindowFlags' called with wrong argument types:
  PySide2.QtWidgets.QWidget.setWindowFlags(int)
Supported signatures:
  PySide2.QtWidgets.QWidget.setWindowFlags(PySide2.QtCore.Qt.WindowFlags)
2025-08-31 10:46:43.745352
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/LucasR.py", line 20, in <module>
    Code.Base.Init.init()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Base/Init.py", line 18, in init
    resp = LucasChessGui.run_gui(main_procesador)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/LucasChessGui.py", line 133, in run_gui
    procesador.iniciar_gui()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 184, in iniciar_gui
    self.main_window = MainWindow.MainWindow(self)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/MainWindow.py", line 25, in __init__
    LCDialog.LCDialog.__init__(self, owner, titulo, icono, extparam)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/QT/LCDialog.py", line 15, in __init__
    self.setWindowFlags(
TypeError: 'PySide2.QtWidgets.QWidget.setWindowFlags' called with wrong argument types:
  PySide2.QtWidgets.QWidget.setWindowFlags(int)
Supported signatures:
  PySide2.QtWidgets.QWidget.setWindowFlags(PySide2.QtCore.Qt.WindowFlags)
2025-08-31 10:47:16.112214
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/LucasR.py", line 20, in <module>
    Code.Base.Init.init()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Base/Init.py", line 18, in init
    resp = LucasChessGui.run_gui(main_procesador)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/LucasChessGui.py", line 133, in run_gui
    procesador.iniciar_gui()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 184, in iniciar_gui
    self.main_window = MainWindow.MainWindow(self)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/MainWindow.py", line 25, in __init__
    LCDialog.LCDialog.__init__(self, owner, titulo, icono, extparam)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/QT/LCDialog.py", line 15, in __init__
    self.setWindowFlags(
TypeError: 'PySide2.QtWidgets.QWidget.setWindowFlags' called with wrong argument types:
  PySide2.QtWidgets.QWidget.setWindowFlags(RenderHints)
Supported signatures:
  PySide2.QtWidgets.QWidget.setWindowFlags(PySide2.QtCore.Qt.WindowFlags)
2025-08-31 10:47:32.385228
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/LucasR.py", line 20, in <module>
    Code.Base.Init.init()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Base/Init.py", line 18, in init
    resp = LucasChessGui.run_gui(main_procesador)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/LucasChessGui.py", line 133, in run_gui
    procesador.iniciar_gui()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 184, in iniciar_gui
    self.main_window = MainWindow.MainWindow(self)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/MainWindow.py", line 31, in __init__
    self.base = WBase.WBase(self, manager)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/WBase.py", line 89, in __init__
    self.create_board()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/WBase.py", line 246, in create_board
    self.board = Board.Board(self, config_board, allow_eboard=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/Board.py", line 58, in __init__
    self.setRenderHints(
TypeError: 'PySide2.QtGui.QPainter.RenderHint' object cannot be interpreted as an integer
2025-08-31 10:48:04.746093
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/LucasR.py", line 20, in <module>
    Code.Base.Init.init()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Base/Init.py", line 18, in init
    resp = LucasChessGui.run_gui(main_procesador)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/LucasChessGui.py", line 133, in run_gui
    procesador.iniciar_gui()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 184, in iniciar_gui
    self.main_window = MainWindow.MainWindow(self)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/MainWindow.py", line 31, in __init__
    self.base = WBase.WBase(self, manager)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/WBase.py", line 92, in __init__
    self.create_analysis_bar()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/WBase.py", line 253, in create_analysis_bar
    self.analysis_bar = WAnalysisBar.AnalysisBar(self, self.board)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/WAnalysisBar.py", line 32, in __init__
    self.lb_value_up = Controles.LB(self).set_font_type(puntos=7).align_center()
                       ^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/QT/Controles.py", line 329, in __init__
    self.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction | QtCore.Qt.TextSelectableByMouse)
TypeError: 'PySide2.QtCore.Qt.TextInteractionFlag' object cannot be interpreted as an integer
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer
2025-08-31 10:48:15.867686
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/LucasR.py", line 20, in <module>
    Code.Base.Init.init()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Base/Init.py", line 18, in init
    resp = LucasChessGui.run_gui(main_procesador)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/LucasChessGui.py", line 133, in run_gui
    procesador.iniciar_gui()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 184, in iniciar_gui
    self.main_window = MainWindow.MainWindow(self)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/MainWindow.py", line 31, in __init__
    self.base = WBase.WBase(self, manager)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/WBase.py", line 94, in __init__
    ly_bi = self.creaBloqueInformacion()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/WBase.py", line 347, in creaBloqueInformacion
    self.wsolve = WindowSolve.WSolve(self)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/WindowSolve.py", line 65, in __init__
    self.gb = Controles.GB(self, _("Solution"), ly_moves).set_font_type(puntos=11, peso=75).align_center()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/QT/Controles.py", line 546, in align_center
    self.setAlignment(QtCore.Qt.AlignHCenter)
OverflowError
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer
2025-08-31 10:48:50.821231
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/LucasR.py", line 20, in <module>
    Code.Base.Init.init()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Base/Init.py", line 18, in init
    resp = LucasChessGui.run_gui(main_procesador)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/LucasChessGui.py", line 133, in run_gui
    procesador.iniciar_gui()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 184, in iniciar_gui
    self.main_window = MainWindow.MainWindow(self)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/MainWindow.py", line 31, in __init__
    self.base = WBase.WBase(self, manager)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/WBase.py", line 94, in __init__
    ly_bi = self.creaBloqueInformacion()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/WBase.py", line 347, in creaBloqueInformacion
    self.wsolve = WindowSolve.WSolve(self)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/WindowSolve.py", line 65, in __init__
    self.gb = Controles.GB(self, _("Solution"), ly_moves).set_font_type(puntos=11, peso=75).align_center()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/QT/Controles.py", line 549, in align_center
    self.setAlignment(QtCore.Qt.AlignHCenter)
OverflowError
2025-08-31 10:49:18.943689
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/LucasR.py", line 20, in <module>
    Code.Base.Init.init()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Base/Init.py", line 18, in init
    resp = LucasChessGui.run_gui(main_procesador)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/LucasChessGui.py", line 133, in run_gui
    procesador.iniciar_gui()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 186, in iniciar_gui
    self.main_window.muestra()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/MainWindow.py", line 190, in muestra
    self.setWindowFlags(QtCore.Qt.WindowCloseButtonHint | flags)
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'MainWindow' object has no attribute 'setWindowFlags'. Did you mean: 'setWindowFlag'?
2025-08-31 11:01:01.514545
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/WBase.py", line 399, in run_action
    self.manager.run_action(self.sender().key)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 581, in run_action
    self.options()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 720, in options
    resp()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 740, in cambiaconfiguration
    if WindowConfig.options(self.main_window, self.configuration):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Config/WindowConfig.py", line 219, in options
    resultado = form.run()
                ^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/QT/FormLayout.py", line 144, in run
    return fedit(
           ^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/QT/FormLayout.py", line 945, in fedit
    dialog = FormDialog(data, title, comment, icon, parent, if_default, dispatch, li_extra_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/QT/FormLayout.py", line 866, in __init__
    self.setWindowFlags(flags)
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'FormDialog' object has no attribute 'setWindowFlags'. Did you mean: 'setWindowFlag'?
2025-08-31 11:01:19.453649
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/WBase.py", line 399, in run_action
    self.manager.run_action(self.sender().key)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 581, in run_action
    self.options()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 720, in options
    resp()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 745, in edit_board_colors
    w = WBoardColors.WBoardColors(self.board)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/WBoardColors.py", line 305, in __init__
    lb_blancas = crea_lb(name)
                 ^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/WBoardColors.py", line 297, in crea_lb
    return Controles.LB(self, txt + ": ").align_right()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/QT/Controles.py", line 357, in align_right
    if Code.is_macos:
       ^^^^
NameError: name 'Code' is not defined
2025-08-31 11:01:33.110515
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/WBase.py", line 399, in run_action
    self.manager.run_action(self.sender().key)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 581, in run_action
    self.options()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 720, in options
    resp()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 740, in cambiaconfiguration
    if WindowConfig.options(self.main_window, self.configuration):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Config/WindowConfig.py", line 219, in options
    resultado = form.run()
                ^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/QT/FormLayout.py", line 144, in run
    return fedit(
           ^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/QT/FormLayout.py", line 945, in fedit
    dialog = FormDialog(data, title, comment, icon, parent, if_default, dispatch, li_extra_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/QT/FormLayout.py", line 866, in __init__
    self.setWindowFlags(flags)
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'FormDialog' object has no attribute 'setWindowFlags'. Did you mean: 'setWindowFlag'?
2025-08-31 11:01:40.057872
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/WBase.py", line 399, in run_action
    self.manager.run_action(self.sender().key)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 585, in run_action
    self.menu_tools()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 833, in menu_tools
    self.menuTools_run(resp)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 870, in menuTools_run
    self.database(accion, valor)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 947, in database
    dbpath, path_pgn = WDB_GUtils.new_database(self.main_window, self.configuration, with_import_pgn=True)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Databases/WDB_GUtils.py", line 304, in new_database
    w = WOptionsDatabase(owner, configuration, dic_data, with_import_pgn, name)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Databases/WDB_GUtils.py", line 41, in __init__
    self.setWindowFlags(QtCore.Qt.WindowCloseButtonHint | QtCore.Qt.Dialog | QtCore.Qt.WindowTitleHint)
TypeError: 'PySide2.QtCore.Qt.WindowType' object cannot be interpreted as an integer
2025-08-31 11:02:40.250935
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/WBase.py", line 399, in run_action
    self.manager.run_action(self.sender().key)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 569, in run_action
    self.menuplay()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 361, in menuplay
    self.menuPlay_run(resp)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 370, in menuPlay_run
    self.playPerson(rival)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 382, in playPerson
    uno = QTVarios.blancasNegrasTiempo(self.main_window)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/QT/QTVarios.py", line 198, in blancasNegrasTiempo
    w = BlancasNegrasTiempo(owner)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/QT/QTVarios.py", line 94, in __init__
    self.setWindowFlags(
TypeError: 'PySide2.QtCore.Qt.WindowType' object cannot be interpreted as an integer
2025-08-31 11:08:45.718520
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/QT/Grid.py", line 141, in flags
    column = self.oColumnasR.column(index.column())
                                    ^^^^^^^^^^^^^^
TypeError: 'PySide2.QtCore.Qt.ItemFlag' object cannot be interpreted as an integer
2025-08-31 11:08:45.893217
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/QT/Grid.py", line 141, in flags
    column = self.oColumnasR.column(index.column())
                                    ^^^^^^^^^^^^^^
TypeError: 'PySide2.QtCore.Qt.ItemFlag' object cannot be interpreted as an integer
2025-08-31 11:08:45.922998
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/QT/Grid.py", line 141, in flags
    column = self.oColumnasR.column(index.column())
                                    ^^^^^^^^^^^^^^
TypeError: 'PySide2.QtCore.Qt.ItemFlag' object cannot be interpreted as an integer
2025-08-31 11:08:45.954729
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/QT/Grid.py", line 141, in flags
    column = self.oColumnasR.column(index.column())
                                    ^^^^^^^^^^^^^^
TypeError: 'PySide2.QtCore.Qt.ItemFlag' object cannot be interpreted as an integer
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer
2025-08-31 11:11:03.339078
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/QT/Grid.py", line 141, in flags
    column = self.oColumnasR.column(index.column())
                                    ^^^^^^^^^^^^^^
TypeError: 'PySide2.QtCore.Qt.ItemFlag' object cannot be interpreted as an integer
2025-08-31 11:11:03.564183
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/QT/Grid.py", line 141, in flags
    column = self.oColumnasR.column(index.column())
                                    ^^^^^^^^^^^^^^
TypeError: 'PySide2.QtCore.Qt.ItemFlag' object cannot be interpreted as an integer
2025-08-31 11:11:03.613179
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/QT/Grid.py", line 141, in flags
    column = self.oColumnasR.column(index.column())
                                    ^^^^^^^^^^^^^^
TypeError: 'PySide2.QtCore.Qt.ItemFlag' object cannot be interpreted as an integer
2025-08-31 11:11:03.666365
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/QT/Grid.py", line 141, in flags
    column = self.oColumnasR.column(index.column())
                                    ^^^^^^^^^^^^^^
TypeError: 'PySide2.QtCore.Qt.ItemFlag' object cannot be interpreted as an integer
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer
2025-08-31 11:12:15.988409
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/QT/Grid.py", line 141, in flags
    column = self.oColumnasR.column(index.column())
                                    ^^^^^^^^^^^^^^
TypeError: 'PySide2.QtCore.Qt.ItemFlag' object cannot be interpreted as an integer
2025-08-31 11:12:16.209948
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/QT/Grid.py", line 141, in flags
    column = self.oColumnasR.column(index.column())
                                    ^^^^^^^^^^^^^^
TypeError: 'PySide2.QtCore.Qt.ItemFlag' object cannot be interpreted as an integer
2025-08-31 11:12:16.293041
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/QT/Grid.py", line 141, in flags
    column = self.oColumnasR.column(index.column())
                                    ^^^^^^^^^^^^^^
TypeError: 'PySide2.QtCore.Qt.ItemFlag' object cannot be interpreted as an integer
2025-08-31 11:12:16.371255
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/QT/Grid.py", line 141, in flags
    column = self.oColumnasR.column(index.column())
                                    ^^^^^^^^^^^^^^
TypeError: 'PySide2.QtCore.Qt.ItemFlag' object cannot be interpreted as an integer
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer
2025-08-31 11:26:49.308147
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/WBase.py", line 399, in run_action
    self.manager.run_action(self.sender().key)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 569, in run_action
    self.menuplay()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 361, in menuplay
    self.menuPlay_run(resp)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 367, in menuPlay_run
    self.libre(config)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 992, in libre
    dic = WPlayAgainstEngine.play_against_engine(self, _("Play against an engine"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/PlayAgainstEngine/WPlayAgainstEngine.py", line 1265, in play_against_engine
    w = WPlayAgainstEngine(procesador, titulo, True)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/PlayAgainstEngine/WPlayAgainstEngine.py", line 62, in __init__
    self.motores = SelectEngines.SelectEngines(procesador.main_window)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Engines/SelectEngines.py", line 52, in __init__
    um = QTUtil2.one_moment_please(owner, _("Reading the list of engines"))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/QT/QTUtil2.py", line 267, in one_moment_please
    return waiting_message.start(owner, mensaje, physical_pos=physical_pos)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/QT/QTUtil2.py", line 204, in start
    self.me = MensEspera(
              ^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/QT/QTUtil2.py", line 49, in __init__
    self.setWindowFlags(
TypeError: 'PySide2.QtCore.Qt.WindowType' object cannot be interpreted as an integer
2025-08-31 11:55:29.700386
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/WBase.py", line 399, in run_action
    self.manager.run_action(self.sender().key)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 569, in run_action
    self.menuplay()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 361, in menuplay
    self.menuPlay_run(resp)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 367, in menuPlay_run
    self.libre(config)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 992, in libre
    dic = WPlayAgainstEngine.play_against_engine(self, _("Play against an engine"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/PlayAgainstEngine/WPlayAgainstEngine.py", line 1265, in play_against_engine
    w = WPlayAgainstEngine(procesador, titulo, True)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/PlayAgainstEngine/WPlayAgainstEngine.py", line 62, in __init__
    self.motores = SelectEngines.SelectEngines(procesador.main_window)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Engines/SelectEngines.py", line 52, in __init__
    um = QTUtil2.one_moment_please(owner, _("Reading the list of engines"))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/QT/QTUtil2.py", line 267, in one_moment_please
    return waiting_message.start(owner, mensaje, physical_pos=physical_pos)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/QT/QTUtil2.py", line 204, in start
    self.me = MensEspera(
              ^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/QT/QTUtil2.py", line 49, in __init__
    self.setWindowFlags(
TypeError: 'PySide2.QtCore.Qt.WindowType' object cannot be interpreted as an integer
2025-08-31 18:33:54.055480
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/WBase.py", line 399, in run_action
    self.manager.run_action(self.sender().key)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 569, in run_action
    self.menuplay()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 361, in menuplay
    self.menuPlay_run(resp)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 367, in menuPlay_run
    self.libre(config)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 992, in libre
    dic = WPlayAgainstEngine.play_against_engine(self, _("Play against an engine"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/PlayAgainstEngine/WPlayAgainstEngine.py", line 1265, in play_against_engine
    w = WPlayAgainstEngine(procesador, titulo, True)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/PlayAgainstEngine/WPlayAgainstEngine.py", line 62, in __init__
    self.motores = SelectEngines.SelectEngines(procesador.main_window)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Engines/SelectEngines.py", line 69, in __init__
    self.li_engines_wicker = EnginesWicker.read_wicker_engines()
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Engines/EnginesWicker.py", line 127, in read_wicker_engines
    book = configuration.path_book(nom_book)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Config/Configuration.py", line 318, in path_book
    return self.dic_books[alias]
           ^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Config/Configuration.py", line 314, in dic_books
    add_folder(Util.opj(Code.folder_engines, engine))
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Config/Configuration.py", line 306, in add_folder
    for entry in os.scandir(folder):
                 ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/OS/darwin/Engines/foxcub'
2025-08-31 18:35:11.862126
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/WBase.py", line 399, in run_action
    self.manager.run_action(self.sender().key)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 569, in run_action
    self.menuplay()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 361, in menuplay
    self.menuPlay_run(resp)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 367, in menuPlay_run
    self.libre(config)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 992, in libre
    dic = WPlayAgainstEngine.play_against_engine(self, _("Play against an engine"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/PlayAgainstEngine/WPlayAgainstEngine.py", line 1265, in play_against_engine
    w = WPlayAgainstEngine(procesador, titulo, True)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/PlayAgainstEngine/WPlayAgainstEngine.py", line 62, in __init__
    self.motores = SelectEngines.SelectEngines(procesador.main_window)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Engines/SelectEngines.py", line 69, in __init__
    self.li_engines_wicker = EnginesWicker.read_wicker_engines()
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Engines/EnginesWicker.py", line 127, in read_wicker_engines
    book = configuration.path_book(nom_book)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Config/Configuration.py", line 318, in path_book
    return self.dic_books[alias]
           ~~~~~~~~~~~~~~^^^^^^^
KeyError: 'rodent.bin'
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer
2025-08-31 21:38:06.625874
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Engines/WConfEngines.py", line 116, in cambiada_tab
    w.activate_this()
    ^^^^^^^^^^^^^^^
AttributeError: 'PySide2.QtWidgets.QLabel' object has no attribute 'activate_this'
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer
2025-08-31 21:38:40.479286
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Engines/WConfEngines.py", line 116, in cambiada_tab
    w.activate_this()
    ^^^^^^^^^^^^^^^
AttributeError: 'PySide2.QtWidgets.QLabel' object has no attribute 'activate_this'
2025-08-31 21:38:53.758659
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Engines/WConfEngines.py", line 116, in cambiada_tab
    w.activate_this()
    ^^^^^^^^^^^^^^^
AttributeError: 'PySide2.QtWidgets.QLabel' object has no attribute 'activate_this'
2025-08-31 21:39:22.628891
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Engines/WConfEngines.py", line 116, in cambiada_tab
    w.activate_this()
    ^^^^^^^^^^^^^^^
AttributeError: 'PySide2.QtWidgets.QLabel' object has no attribute 'activate_this'
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer
2025-08-31 21:41:58.756758
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Engines/WConfEngines.py", line 110, in cambiada_tab
    self.w_current.save()
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'PySide2.QtWidgets.QLabel' object has no attribute 'save'
2025-08-31 21:41:59.784087
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Engines/WConfEngines.py", line 110, in cambiada_tab
    self.w_current.save()
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'PySide2.QtWidgets.QLabel' object has no attribute 'save'
2025-08-31 21:42:03.008581
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Engines/WConfEngines.py", line 211, in terminar
    def terminar(self):
        ^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Engines/WConfEngines.py", line 206, in save
    if not Code.is_macos and hasattr(self.wconf_analyzer, 'save'):
    ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'PySide2.QtWidgets.QLabel' object has no attribute 'save'
2025-08-31 21:42:04.572596
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Engines/WConfEngines.py", line 211, in terminar
    def terminar(self):
        ^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Engines/WConfEngines.py", line 206, in save
    if not Code.is_macos and hasattr(self.wconf_analyzer, 'save'):
    ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'PySide2.QtWidgets.QLabel' object has no attribute 'save'
2025-08-31 21:42:07.744832
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Engines/WConfEngines.py", line 211, in terminar
    def terminar(self):
        ^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Engines/WConfEngines.py", line 206, in save
    if not Code.is_macos and hasattr(self.wconf_analyzer, 'save'):
    ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'PySide2.QtWidgets.QLabel' object has no attribute 'save'
2025-08-31 21:42:08.642410
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Engines/WConfEngines.py", line 215, in closeEvent
    def closeEvent(self, event):
        ^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Engines/WConfEngines.py", line 206, in save
    if not Code.is_macos and hasattr(self.wconf_analyzer, 'save'):
    ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'PySide2.QtWidgets.QLabel' object has no attribute 'save'
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer

The above exception was the direct cause of the following exception:

2025-08-31 21:42:21.917130
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/WBase.py", line 399, in run_action
    self.manager.run_action(self.sender().key)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 585, in run_action
    self.menu_tools()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 833, in menu_tools
    self.menuTools_run(resp)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 859, in menuTools_run
    self.kibitzers_manager.edit()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Kibitzers/KibitzersManager.py", line 20, in edit
    w = WindowKibitzers.WKibitzers(self.main_window, self)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Kibitzers/WindowKibitzers.py", line 82, in __init__
    o_columns.nueva("CAMPO", _("Label"), 152, align_right=True)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/QT/Columnas.py", line 231, in nueva
    column = Columna(
             ^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/QT/Columnas.py", line 78, in __init__
    self.ponQT()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/QT/Columnas.py", line 81, in ponQT
    self.qtAlineacion = self.QTalineacion(self.alineacion)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/QT/Columnas.py", line 103, in QTalineacion
    qtalin = int(QtCore.Qt.AlignRight | QtCore.Qt.AlignVCenter)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SystemError: <class 'int'> returned a result with an exception set
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer

The above exception was the direct cause of the following exception:

2025-08-31 21:42:59.821595
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/WBase.py", line 399, in run_action
    self.manager.run_action(self.sender().key)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 585, in run_action
    self.menu_tools()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 833, in menu_tools
    self.menuTools_run(resp)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 859, in menuTools_run
    self.kibitzers_manager.edit()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Kibitzers/KibitzersManager.py", line 20, in edit
    w = WindowKibitzers.WKibitzers(self.main_window, self)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Kibitzers/WindowKibitzers.py", line 82, in __init__
    o_columns.nueva("CAMPO", _("Label"), 152, align_right=True)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/QT/Columnas.py", line 231, in nueva
    column = Columna(
             ^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/QT/Columnas.py", line 78, in __init__
    self.ponQT()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/QT/Columnas.py", line 81, in ponQT
    self.qtAlineacion = self.QTalineacion(self.alineacion)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/QT/Columnas.py", line 103, in QTalineacion
    qtalin = int(QtCore.Qt.AlignRight | QtCore.Qt.AlignVCenter)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SystemError: <class 'int'> returned a result with an exception set
2025-08-31 22:07:49.639805
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Engines/WConfEngines.py", line 110, in cambiada_tab
    self.w_current.save()
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'PySide2.QtWidgets.QLabel' object has no attribute 'save'
2025-08-31 22:07:50.985622
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Engines/WConfEngines.py", line 110, in cambiada_tab
    self.w_current.save()
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'PySide2.QtWidgets.QLabel' object has no attribute 'save'
2025-08-31 22:07:52.165796
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Engines/WConfEngines.py", line 110, in cambiada_tab
    self.w_current.save()
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'PySide2.QtWidgets.QLabel' object has no attribute 'save'
2025-08-31 22:08:07.206608
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Engines/WConfEngines.py", line 110, in cambiada_tab
    self.w_current.save()
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'PySide2.QtWidgets.QLabel' object has no attribute 'save'
2025-08-31 22:08:08.230114
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Engines/WConfEngines.py", line 110, in cambiada_tab
    self.w_current.save()
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'PySide2.QtWidgets.QLabel' object has no attribute 'save'
2025-08-31 22:08:09.171049
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Engines/WConfEngines.py", line 110, in cambiada_tab
    self.w_current.save()
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'PySide2.QtWidgets.QLabel' object has no attribute 'save'
2025-08-31 22:08:20.408988
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/WBase.py", line 399, in run_action
    self.manager.run_action(self.sender().key)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 577, in run_action
    self.entrenamientos.lanza()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 393, in lanza
    self.verify()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 387, in verify
    self.rehaz()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 390, in rehaz
    self.menu, self.dicMenu = self.create_menu()
                              ^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 376, in create_menu
    self.create_menu_basic(menu, xopcion)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 163, in create_menu_basic
    menu3 = menu2.submenu(_("Basic test"), vicon(icl, icn))
                                           ^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/QT/Piezas.py", line 91, in icono
    pm = self.pixmap(pieza, name, width)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/QT/Piezas.py", line 95, in pixmap
    fich = Code.path_resource("Pieces", name, "%s%s.svg" % ("w" if pieza.isupper() else "b", pieza.lower()))
           ^^^^
UnboundLocalError: cannot access local variable 'Code' where it is not associated with a value
2025-08-31 22:08:21.008421
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/WBase.py", line 399, in run_action
    self.manager.run_action(self.sender().key)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 577, in run_action
    self.entrenamientos.lanza()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 393, in lanza
    self.verify()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 387, in verify
    self.rehaz()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 390, in rehaz
    self.menu, self.dicMenu = self.create_menu()
                              ^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 376, in create_menu
    self.create_menu_basic(menu, xopcion)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 163, in create_menu_basic
    menu3 = menu2.submenu(_("Basic test"), vicon(icl, icn))
                                           ^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/QT/Piezas.py", line 91, in icono
    pm = self.pixmap(pieza, name, width)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/QT/Piezas.py", line 95, in pixmap
    fich = Code.path_resource("Pieces", name, "%s%s.svg" % ("w" if pieza.isupper() else "b", pieza.lower()))
           ^^^^
UnboundLocalError: cannot access local variable 'Code' where it is not associated with a value
2025-08-31 22:08:21.487308
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/WBase.py", line 399, in run_action
    self.manager.run_action(self.sender().key)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 577, in run_action
    self.entrenamientos.lanza()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 393, in lanza
    self.verify()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 387, in verify
    self.rehaz()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 390, in rehaz
    self.menu, self.dicMenu = self.create_menu()
                              ^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 376, in create_menu
    self.create_menu_basic(menu, xopcion)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 163, in create_menu_basic
    menu3 = menu2.submenu(_("Basic test"), vicon(icl, icn))
                                           ^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/QT/Piezas.py", line 91, in icono
    pm = self.pixmap(pieza, name, width)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/QT/Piezas.py", line 95, in pixmap
    fich = Code.path_resource("Pieces", name, "%s%s.svg" % ("w" if pieza.isupper() else "b", pieza.lower()))
           ^^^^
UnboundLocalError: cannot access local variable 'Code' where it is not associated with a value
2025-09-01 09:13:15.043642
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/WBase.py", line 399, in run_action
    self.manager.run_action(self.sender().key)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/ManagerSolo.py", line 144, in run_action
    self.utilities_gs()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/ManagerSolo.py", line 488, in utilities_gs
    resp = self.utilities(li_extra_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Manager.py", line 1928, in utilities
    getattr(self, "play_instead_of_me")()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Manager.py", line 1555, in play_instead_of_me
    self.player_has_moved_base(rm.from_sq, rm.to_sq, rm.promotion)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Manager.py", line 2382, in player_has_moved_base
    return self.messenger(from_sq, to_sq, promotion)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/ManagerSolo.py", line 218, in player_has_moved
    move = self.check_human_move(from_sq, to_sq, promotion)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Manager.py", line 1500, in check_human_move
    ok, self.error, move = Move.get_game_move(self.game, self.game.last_position, from_sq, to_sq, promotion)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Base/Move.py", line 468, in get_game_move
    ok, mens_error = position.play(from_sq, to_sq, promotion)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Base/Position.py", line 248, in play
    mv = FasterCode.move_expv(from_a1h8, to_a1h8, promotion)
         ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'FasterCode' has no attribute 'move_expv'
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer
2025-09-01 10:02:14.064786
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Engines/WConfEngines.py", line 110, in cambiada_tab
    self.w_current.save()
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'PySide2.QtWidgets.QLabel' object has no attribute 'save'
2025-09-01 10:02:15.049745
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Engines/WConfEngines.py", line 110, in cambiada_tab
    self.w_current.save()
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'PySide2.QtWidgets.QLabel' object has no attribute 'save'
2025-09-01 10:02:15.903238
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Engines/WConfEngines.py", line 110, in cambiada_tab
    self.w_current.save()
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'PySide2.QtWidgets.QLabel' object has no attribute 'save'
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer
2025-09-01 10:03:22.283496
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/WBase.py", line 399, in run_action
    self.manager.run_action(self.sender().key)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 577, in run_action
    self.entrenamientos.lanza()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 396, in lanza
    self.menu_run(resp)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 414, in menu_run
    self.find_all_moves(resp == "find_all_moves_player")
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 640, in find_all_moves
    self.procesador.manager.start(si_jugador)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/ManagerFindAllMoves.py", line 147, in start
    self.main_window.active_game(True, False)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/MainWindow.py", line 411, in active_game
    self.ajustaTamH()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/MainWindow.py", line 295, in ajustaTamH
    self.refresh()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/MainWindow.py", line 371, in refresh
    QTUtil.refresh_gui()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/QT/QTUtil.py", line 75, in refresh_gui
    QtCore.QCoreApplication.processEvents()
OverflowError
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer
2025-09-01 10:05:55.832143
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/WBase.py", line 399, in run_action
    self.manager.run_action(self.sender().key)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 577, in run_action
    self.entrenamientos.lanza()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 396, in lanza
    self.menu_run(resp)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 414, in menu_run
    self.find_all_moves(resp == "find_all_moves_player")
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 640, in find_all_moves
    self.procesador.manager.start(si_jugador)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/ManagerFindAllMoves.py", line 147, in start
    self.main_window.active_game(True, False)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/MainWindow.py", line 411, in active_game
    self.ajustaTamH()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/MainWindow.py", line 295, in ajustaTamH
    self.refresh()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/MainWindow.py", line 371, in refresh
    QTUtil.refresh_gui()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/QT/QTUtil.py", line 75, in refresh_gui
    QtCore.QCoreApplication.processEvents()
OverflowError
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer
2025-09-01 10:25:19.050289
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/WBase.py", line 399, in run_action
    self.manager.run_action(self.sender().key)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 577, in run_action
    self.entrenamientos.lanza()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 396, in lanza
    self.menu_run(resp)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 414, in menu_run
    self.find_all_moves(resp == "find_all_moves_player")
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 640, in find_all_moves
    self.procesador.manager.start(si_jugador)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/ManagerFindAllMoves.py", line 147, in start
    self.main_window.active_game(True, False)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/MainWindow.py", line 411, in active_game
    self.ajustaTamH()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/MainWindow.py", line 295, in ajustaTamH
    self.refresh()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/MainWindow.py", line 371, in refresh
    QTUtil.refresh_gui()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/QT/QTUtil.py", line 75, in refresh_gui
    QtCore.QCoreApplication.processEvents()
OverflowError
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer
2025-09-01 10:26:21.149160
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/WBase.py", line 399, in run_action
    self.manager.run_action(self.sender().key)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 577, in run_action
    self.entrenamientos.lanza()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 396, in lanza
    self.menu_run(resp)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 414, in menu_run
    self.find_all_moves(resp == "find_all_moves_player")
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 640, in find_all_moves
    self.procesador.manager.start(si_jugador)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/ManagerFindAllMoves.py", line 147, in start
    self.main_window.active_game(True, False)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/MainWindow.py", line 411, in active_game
    self.ajustaTamH()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/MainWindow.py", line 295, in ajustaTamH
    self.refresh()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/MainWindow.py", line 371, in refresh
    QTUtil.refresh_gui()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/QT/QTUtil.py", line 75, in refresh_gui
    QtCore.QCoreApplication.processEvents()
OverflowError
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer
2025-09-01 10:28:50.214053
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/WBase.py", line 399, in run_action
    self.manager.run_action(self.sender().key)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 577, in run_action
    self.entrenamientos.lanza()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 396, in lanza
    self.menu_run(resp)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 414, in menu_run
    self.find_all_moves(resp == "find_all_moves_player")
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 640, in find_all_moves
    self.procesador.manager.start(si_jugador)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/ManagerFindAllMoves.py", line 147, in start
    self.main_window.active_game(True, False)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/MainWindow.py", line 411, in active_game
    self.ajustaTamH()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/MainWindow.py", line 295, in ajustaTamH
    self.refresh()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/MainWindow.py", line 371, in refresh
    QTUtil.refresh_gui()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/QT/QTUtil.py", line 75, in refresh_gui
    QtCore.QCoreApplication.processEvents()
OverflowError
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer
2025-09-01 10:34:02.636593
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/WBase.py", line 399, in run_action
    self.manager.run_action(self.sender().key)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 577, in run_action
    self.entrenamientos.lanza()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 396, in lanza
    self.menu_run(resp)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 417, in menu_run
    QTVarios.mensaje(self.procesador.main_window, _("Find All Moves not available on macOS due to Qt compatibility issues"))
    ^^^^^^^^^^^^^^^^
AttributeError: module 'Code.QT.QTVarios' has no attribute 'mensaje'
2025-09-01 10:34:18.344087
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/WBase.py", line 399, in run_action
    self.manager.run_action(self.sender().key)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 577, in run_action
    self.entrenamientos.lanza()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 396, in lanza
    self.menu_run(resp)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 417, in menu_run
    QTVarios.mensaje(self.procesador.main_window, _("Find All Moves not available on macOS due to Qt compatibility issues"))
    ^^^^^^^^^^^^^^^^
AttributeError: module 'Code.QT.QTVarios' has no attribute 'mensaje'
2025-09-01 10:35:21.319341
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/WBase.py", line 399, in run_action
    self.manager.run_action(self.sender().key)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 577, in run_action
    self.entrenamientos.lanza()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 396, in lanza
    self.menu_run(resp)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 512, in menu_run
    self.procesador.train_position(
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 1179, in train_position
    self.manager.start(position, n_posiciones, titentreno, li_entrenamientos, with_tutor, jump,
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/ManagerEntPos.py", line 105, in start
    self.line_fns = FNSLine.FNSLine(linea)
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/FNSLine.py", line 11, in __init__
    self.read(line)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/FNSLine.py", line 22, in read
    ok, game_obj = Game.pgn_game('[FEN "%s"]\n%s' % (self.position.fen(), solucion))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Base/Game.py", line 1145, in pgn_game
    li = FasterCode.xparse_pgn(pgn)
         ^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'FasterCode' has no attribute 'xparse_pgn'
2025-09-01 10:37:13.668407
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/WBase.py", line 399, in run_action
    self.manager.run_action(self.sender().key)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 577, in run_action
    self.entrenamientos.lanza()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 396, in lanza
    self.menu_run(resp)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 460, in menu_run
    with QTUtil2.OneMomentPlease(self.procesador.main_window):
         ^^^^^^^
UnboundLocalError: cannot access local variable 'QTUtil2' where it is not associated with a value
2025-09-01 10:39:13.749436
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/WBase.py", line 399, in run_action
    self.manager.run_action(self.sender().key)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 577, in run_action
    self.entrenamientos.lanza()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 396, in lanza
    self.menu_run(resp)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 460, in menu_run
    with QTUtil2.OneMomentPlease(self.procesador.main_window):
         ^^^^^^^
UnboundLocalError: cannot access local variable 'QTUtil2' where it is not associated with a value
2025-09-01 10:39:42.706297
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/WBase.py", line 399, in run_action
    self.manager.run_action(self.sender().key)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 577, in run_action
    self.entrenamientos.lanza()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 396, in lanza
    self.menu_run(resp)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 460, in menu_run
    with QTUtil2.OneMomentPlease(self.procesador.main_window):
         ^^^^^^^
UnboundLocalError: cannot access local variable 'QTUtil2' where it is not associated with a value
2025-09-01 10:39:56.308877
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/WBase.py", line 399, in run_action
    self.manager.run_action(self.sender().key)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 577, in run_action
    self.entrenamientos.lanza()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 396, in lanza
    self.menu_run(resp)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 460, in menu_run
    with QTUtil2.OneMomentPlease(self.procesador.main_window):
         ^^^^^^^
UnboundLocalError: cannot access local variable 'QTUtil2' where it is not associated with a value
2025-09-01 10:40:12.725681
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/WBase.py", line 399, in run_action
    self.manager.run_action(self.sender().key)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 577, in run_action
    self.entrenamientos.lanza()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 396, in lanza
    self.menu_run(resp)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 456, in menu_run
    icon = Code.all_pieces.icono(icl, icn)
           ^^^^
UnboundLocalError: cannot access local variable 'Code' where it is not associated with a value
2025-09-01 10:40:38.852607
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/WBase.py", line 399, in run_action
    self.manager.run_action(self.sender().key)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 577, in run_action
    self.entrenamientos.lanza()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 396, in lanza
    self.menu_run(resp)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 460, in menu_run
    with QTUtil2.OneMomentPlease(self.procesador.main_window):
         ^^^^^^^
UnboundLocalError: cannot access local variable 'QTUtil2' where it is not associated with a value
2025-09-01 10:40:48.875552
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/WBase.py", line 399, in run_action
    self.manager.run_action(self.sender().key)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 577, in run_action
    self.entrenamientos.lanza()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 396, in lanza
    self.menu_run(resp)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 460, in menu_run
    with QTUtil2.OneMomentPlease(self.procesador.main_window):
         ^^^^^^^
UnboundLocalError: cannot access local variable 'QTUtil2' where it is not associated with a value
2025-09-01 10:43:38.198933
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/WBase.py", line 399, in run_action
    self.manager.run_action(self.sender().key)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 577, in run_action
    self.entrenamientos.lanza()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 396, in lanza
    self.menu_run(resp)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 510, in menu_run
    self.procesador.train_position(
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 1179, in train_position
    self.manager.start(position, n_posiciones, titentreno, li_entrenamientos, with_tutor, jump,
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/ManagerEntPos.py", line 105, in start
    self.line_fns = FNSLine.FNSLine(linea)
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/FNSLine.py", line 11, in __init__
    self.read(line)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/FNSLine.py", line 22, in read
    ok, game_obj = Game.pgn_game('[FEN "%s"]\n%s' % (self.position.fen(), solucion))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Base/Game.py", line 1145, in pgn_game
    li = FasterCode.xparse_pgn(pgn)
         ^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'FasterCode' has no attribute 'xparse_pgn'
2025-09-01 10:44:01.907677
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/WBase.py", line 399, in run_action
    self.manager.run_action(self.sender().key)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/ManagerEntPos.py", line 289, in run_action
    self.procesador.run_action(key)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 577, in run_action
    self.entrenamientos.lanza()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 396, in lanza
    self.menu_run(resp)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 510, in menu_run
    self.procesador.train_position(
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 1179, in train_position
    self.manager.start(position, n_posiciones, titentreno, li_entrenamientos, with_tutor, jump,
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/ManagerEntPos.py", line 105, in start
    self.line_fns = FNSLine.FNSLine(linea)
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/FNSLine.py", line 11, in __init__
    self.read(line)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/FNSLine.py", line 22, in read
    ok, game_obj = Game.pgn_game('[FEN "%s"]\n%s' % (self.position.fen(), solucion))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Base/Game.py", line 1145, in pgn_game
    li = FasterCode.xparse_pgn(pgn)
         ^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'FasterCode' has no attribute 'xparse_pgn'
2025-09-01 10:44:26.883294
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/BoardElements.py", line 348, in mouseReleaseEvent
    self.board.try_to_move(self, event.scenePos(), event.button())
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/Board.py", line 1871, in try_to_move
    if not self.mensajero(from_sq, to_sq):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Manager.py", line 2382, in player_has_moved_base
    return self.messenger(from_sq, to_sq, promotion)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/ManagerEntPos.py", line 602, in player_has_moved
    move = self.check_human_move(from_sq, to_sq, promotion)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Manager.py", line 1500, in check_human_move
    ok, self.error, move = Move.get_game_move(self.game, self.game.last_position, from_sq, to_sq, promotion)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Base/Move.py", line 468, in get_game_move
    ok, mens_error = position.play(from_sq, to_sq, promotion)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Base/Position.py", line 248, in play
    mv = FasterCode.move_expv(from_a1h8, to_a1h8, promotion)
         ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'FasterCode' has no attribute 'move_expv'
2025-09-01 10:45:02.706817
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/WBase.py", line 399, in run_action
    self.manager.run_action(self.sender().key)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 577, in run_action
    self.entrenamientos.lanza()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 396, in lanza
    self.menu_run(resp)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 510, in menu_run
    self.procesador.train_position(
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 1179, in train_position
    self.manager.start(position, n_posiciones, titentreno, li_entrenamientos, with_tutor, jump,
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/ManagerEntPos.py", line 105, in start
    self.line_fns = FNSLine.FNSLine(linea)
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/FNSLine.py", line 11, in __init__
    self.read(line)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/FNSLine.py", line 22, in read
    ok, game_obj = Game.pgn_game('[FEN "%s"]\n%s' % (self.position.fen(), solucion))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Base/Game.py", line 1145, in pgn_game
    li = FasterCode.xparse_pgn(pgn)
         ^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'FasterCode' has no attribute 'xparse_pgn'
2025-09-01 10:47:38.076665
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/WBase.py", line 399, in run_action
    self.manager.run_action(self.sender().key)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 577, in run_action
    self.entrenamientos.lanza()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 396, in lanza
    self.menu_run(resp)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 510, in menu_run
    self.procesador.train_position(
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 1179, in train_position
    self.manager.start(position, n_posiciones, titentreno, li_entrenamientos, with_tutor, jump,
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/ManagerEntPos.py", line 105, in start
    self.line_fns = FNSLine.FNSLine(linea)
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/FNSLine.py", line 11, in __init__
    self.read(line)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/FNSLine.py", line 22, in read
    ok, game_obj = Game.pgn_game('[FEN "%s"]\n%s' % (self.position.fen(), solucion))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Base/Game.py", line 1145, in pgn_game
    li = FasterCode.xparse_pgn(pgn)
         ^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'FasterCode' has no attribute 'xparse_pgn'
2025-09-01 10:49:37.578451
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/WBase.py", line 399, in run_action
    self.manager.run_action(self.sender().key)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 577, in run_action
    self.entrenamientos.lanza()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 396, in lanza
    self.menu_run(resp)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 510, in menu_run
    self.procesador.train_position(
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 1179, in train_position
    self.manager.start(position, n_posiciones, titentreno, li_entrenamientos, with_tutor, jump,
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/ManagerEntPos.py", line 105, in start
    self.line_fns = FNSLine.FNSLine(linea)
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/FNSLine.py", line 11, in __init__
    self.read(line)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/FNSLine.py", line 22, in read
    ok, game_obj = Game.pgn_game('[FEN "%s"]\n%s' % (self.position.fen(), solucion))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Base/Game.py", line 1152, in pgn_game
    FasterCode.set_init_fen()
    ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'FasterCode' has no attribute 'set_init_fen'
2025-09-01 10:58:52.991711
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/WBase.py", line 399, in run_action
    self.manager.run_action(self.sender().key)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 577, in run_action
    self.entrenamientos.lanza()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 396, in lanza
    self.menu_run(resp)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 510, in menu_run
    self.procesador.train_position(
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 1179, in train_position
    self.manager.start(position, n_posiciones, titentreno, li_entrenamientos, with_tutor, jump,
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/ManagerEntPos.py", line 105, in start
    self.line_fns = FNSLine.FNSLine(linea)
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/FNSLine.py", line 11, in __init__
    self.read(line)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/FNSLine.py", line 22, in read
    ok, game_obj = Game.pgn_game('[FEN "%s"]\n%s' % (self.position.fen(), solucion))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Base/Game.py", line 1192, in pgn_game
    elif key in "{;":
         ^^^^^^^^^^^
TypeError: 'in <string>' requires string as left operand, not ChildNode
2025-09-01 10:59:15.760543
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/WBase.py", line 399, in run_action
    self.manager.run_action(self.sender().key)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/ManagerEntPos.py", line 289, in run_action
    self.procesador.run_action(key)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 577, in run_action
    self.entrenamientos.lanza()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 396, in lanza
    self.menu_run(resp)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 510, in menu_run
    self.procesador.train_position(
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 1179, in train_position
    self.manager.start(position, n_posiciones, titentreno, li_entrenamientos, with_tutor, jump,
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/ManagerEntPos.py", line 105, in start
    self.line_fns = FNSLine.FNSLine(linea)
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/FNSLine.py", line 11, in __init__
    self.read(line)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/FNSLine.py", line 22, in read
    ok, game_obj = Game.pgn_game('[FEN "%s"]\n%s' % (self.position.fen(), solucion))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Base/Game.py", line 1192, in pgn_game
    elif key in "{;":
         ^^^^^^^^^^^
TypeError: 'in <string>' requires string as left operand, not ChildNode
2025-09-01 11:01:51.781381
Traceback (most recent call last):
  File "/Users/mike/lucaschess-venv/lib/python3.11/site-packages/chess/__init__.py", line 2632, in set_fen
    fullmove_number = int(fullmove_part)
                      ^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '1"]'

During handling of the above exception, another exception occurred:

2025-09-01 11:01:51.855177
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/WBase.py", line 399, in run_action
    self.manager.run_action(self.sender().key)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 577, in run_action
    self.entrenamientos.lanza()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 396, in lanza
    self.menu_run(resp)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 510, in menu_run
    self.procesador.train_position(
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 1179, in train_position
    self.manager.start(position, n_posiciones, titentreno, li_entrenamientos, with_tutor, jump,
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/ManagerEntPos.py", line 105, in start
    self.line_fns = FNSLine.FNSLine(linea)
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/FNSLine.py", line 11, in __init__
    self.read(line)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/FNSLine.py", line 22, in read
    ok, game_obj = Game.pgn_game('[FEN "%s"]\n%s' % (self.position.fen(), solucion))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Base/Game.py", line 1163, in pgn_game
    FasterCode.set_fen(vl)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/OS/darwin/FasterCode.py", line 40, in set_fen
    _board = chess.Board(fen)
             ^^^^^^^^^^^^^^^^
  File "/Users/mike/lucaschess-venv/lib/python3.11/site-packages/chess/__init__.py", line 1711, in __init__
    self.set_fen(fen)
  File "/Users/mike/lucaschess-venv/lib/python3.11/site-packages/chess/__init__.py", line 2634, in set_fen
    raise ValueError(f"invalid fullmove number in fen: {fen!r}")
ValueError: invalid fullmove number in fen: '"8/8/8/Q7/8/1K6/8/2k5 w - - 0 1"]'
2025-09-01 11:01:58.576598
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/Board.py", line 1359, in mousePressEvent
    li_c = self.main_window.manager.colect_candidates(a1h8)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Manager.py", line 288, in colect_candidates
    from_sq = mov.xfrom()
              ^^^^^^^^^
AttributeError: 'str' object has no attribute 'xfrom'
2025-09-01 11:03:33.672786
Traceback (most recent call last):
  File "/Users/mike/lucaschess-venv/lib/python3.11/site-packages/chess/__init__.py", line 2632, in set_fen
    fullmove_number = int(fullmove_part)
                      ^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '1"]'

During handling of the above exception, another exception occurred:

2025-09-01 11:03:33.797204
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/WBase.py", line 399, in run_action
    self.manager.run_action(self.sender().key)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 577, in run_action
    self.entrenamientos.lanza()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 396, in lanza
    self.menu_run(resp)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 510, in menu_run
    self.procesador.train_position(
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 1179, in train_position
    self.manager.start(position, n_posiciones, titentreno, li_entrenamientos, with_tutor, jump,
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/ManagerEntPos.py", line 105, in start
    self.line_fns = FNSLine.FNSLine(linea)
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/FNSLine.py", line 11, in __init__
    self.read(line)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/FNSLine.py", line 22, in read
    ok, game_obj = Game.pgn_game('[FEN "%s"]\n%s' % (self.position.fen(), solucion))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Base/Game.py", line 1163, in pgn_game
    FasterCode.set_fen(vl)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/OS/darwin/FasterCode.py", line 40, in set_fen
    _board = chess.Board(fen)
             ^^^^^^^^^^^^^^^^
  File "/Users/mike/lucaschess-venv/lib/python3.11/site-packages/chess/__init__.py", line 1711, in __init__
    self.set_fen(fen)
  File "/Users/mike/lucaschess-venv/lib/python3.11/site-packages/chess/__init__.py", line 2634, in set_fen
    raise ValueError(f"invalid fullmove number in fen: {fen!r}")
ValueError: invalid fullmove number in fen: '"8/8/8/Q7/8/1K6/8/2k5 w - - 0 1"]'
2025-09-01 11:04:25.936838
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/WBase.py", line 399, in run_action
    self.manager.run_action(self.sender().key)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 577, in run_action
    self.entrenamientos.lanza()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 396, in lanza
    self.menu_run(resp)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 510, in menu_run
    self.procesador.train_position(
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 1179, in train_position
    self.manager.start(position, n_posiciones, titentreno, li_entrenamientos, with_tutor, jump,
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/ManagerEntPos.py", line 105, in start
    self.line_fns = FNSLine.FNSLine(linea)
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/FNSLine.py", line 11, in __init__
    self.read(line)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/FNSLine.py", line 22, in read
    ok, game_obj = Game.pgn_game('[FEN "%s"]\n%s' % (self.position.fen(), solucion))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Base/Game.py", line 1165, in pgn_game
    game.set_fen(vl)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Base/Game.py", line 43, in set_fen
    cp.read_fen(fen)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Base/Position.py", line 107, in read_fen
    self.num_moves = int(move)
                     ^^^^^^^^^
ValueError: invalid literal for int() with base 10: '1"]'
2025-09-01 11:09:44.114056
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/WBase.py", line 399, in run_action
    self.manager.run_action(self.sender().key)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 577, in run_action
    self.entrenamientos.lanza()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 396, in lanza
    self.menu_run(resp)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 510, in menu_run
    self.procesador.train_position(
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 1179, in train_position
    self.manager.start(position, n_posiciones, titentreno, li_entrenamientos, with_tutor, jump,
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/ManagerEntPos.py", line 105, in start
    self.line_fns = FNSLine.FNSLine(linea)
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/FNSLine.py", line 11, in __init__
    self.read(line)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/FNSLine.py", line 22, in read
    ok, game_obj = Game.pgn_game('[FEN "%s"]\n%s' % (self.position.fen(), solucion))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Base/Game.py", line 1165, in pgn_game
    game.set_fen(vl)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Base/Game.py", line 43, in set_fen
    cp.read_fen(fen)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Base/Position.py", line 107, in read_fen
    self.num_moves = int(move)
                     ^^^^^^^^^
ValueError: invalid literal for int() with base 10: '1"'
2025-09-01 11:14:51.361053
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/WBase.py", line 399, in run_action
    self.manager.run_action(self.sender().key)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 577, in run_action
    self.entrenamientos.lanza()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 396, in lanza
    self.menu_run(resp)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 510, in menu_run
    self.procesador.train_position(
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 1179, in train_position
    self.manager.start(position, n_posiciones, titentreno, li_entrenamientos, with_tutor, jump,
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/ManagerEntPos.py", line 105, in start
    self.line_fns = FNSLine.FNSLine(linea)
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/FNSLine.py", line 11, in __init__
    self.read(line)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/FNSLine.py", line 22, in read
    ok, game_obj = Game.pgn_game('[FEN "%s"]\n%s' % (self.position.fen(), solucion))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Base/Game.py", line 1165, in pgn_game
    game.set_fen(vl)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Base/Game.py", line 43, in set_fen
    cp.read_fen(fen)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Base/Position.py", line 107, in read_fen
    self.num_moves = int(move)
                     ^^^^^^^^^
ValueError: invalid literal for int() with base 10: '1"'
2025-09-01 11:16:57.544769
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/WBase.py", line 399, in run_action
    self.manager.run_action(self.sender().key)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 577, in run_action
    self.entrenamientos.lanza()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 396, in lanza
    self.menu_run(resp)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 510, in menu_run
    self.procesador.train_position(
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 1179, in train_position
    self.manager.start(position, n_posiciones, titentreno, li_entrenamientos, with_tutor, jump,
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/ManagerEntPos.py", line 105, in start
    self.line_fns = FNSLine.FNSLine(linea)
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/FNSLine.py", line 11, in __init__
    self.read(line)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/FNSLine.py", line 24, in read
    ok, game_obj = Game.pgn_game(pgn_text)
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Base/Game.py", line 1165, in pgn_game
    game.set_fen(vl)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Base/Game.py", line 43, in set_fen
    cp.read_fen(fen)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Base/Position.py", line 107, in read_fen
    self.num_moves = int(move)
                     ^^^^^^^^^
ValueError: invalid literal for int() with base 10: '1"'
2025-09-01 11:18:41.381763
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/WBase.py", line 399, in run_action
    self.manager.run_action(self.sender().key)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 577, in run_action
    self.entrenamientos.lanza()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 396, in lanza
    self.menu_run(resp)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Menus/MenuTrainings.py", line 510, in menu_run
    self.procesador.train_position(
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 1179, in train_position
    self.manager.start(position, n_posiciones, titentreno, li_entrenamientos, with_tutor, jump,
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/ManagerEntPos.py", line 105, in start
    self.line_fns = FNSLine.FNSLine(linea)
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/FNSLine.py", line 11, in __init__
    self.read(line)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/FNSLine.py", line 24, in read
    ok, game_obj = Game.pgn_game(pgn_text)
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Base/Game.py", line 1169, in pgn_game
    game.set_fen(vl)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Base/Game.py", line 43, in set_fen
    cp.read_fen(fen)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Base/Position.py", line 107, in read_fen
    self.num_moves = int(move)
                     ^^^^^^^^^
ValueError: invalid literal for int() with base 10: '1"'
2025-09-01 11:22:51.827699
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/BoardElements.py", line 348, in mouseReleaseEvent
    self.board.try_to_move(self, event.scenePos(), event.button())
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/Board.py", line 1871, in try_to_move
    if not self.mensajero(from_sq, to_sq):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Manager.py", line 2382, in player_has_moved_base
    return self.messenger(from_sq, to_sq, promotion)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/ManagerEntPos.py", line 602, in player_has_moved
    move = self.check_human_move(from_sq, to_sq, promotion)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Manager.py", line 1500, in check_human_move
    ok, self.error, move = Move.get_game_move(self.game, self.game.last_position, from_sq, to_sq, promotion)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Base/Move.py", line 468, in get_game_move
    ok, mens_error = position.play(from_sq, to_sq, promotion)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Base/Position.py", line 254, in play
    enr_k = mv.iscastle_k()
            ^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'iscastle_k'
2025-09-01 11:23:37.250098
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/BoardElements.py", line 348, in mouseReleaseEvent
    self.board.try_to_move(self, event.scenePos(), event.button())
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/Board.py", line 1871, in try_to_move
    if not self.mensajero(from_sq, to_sq):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Manager.py", line 2382, in player_has_moved_base
    return self.messenger(from_sq, to_sq, promotion)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/ManagerEntPos.py", line 602, in player_has_moved
    move = self.check_human_move(from_sq, to_sq, promotion)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Manager.py", line 1500, in check_human_move
    ok, self.error, move = Move.get_game_move(self.game, self.game.last_position, from_sq, to_sq, promotion)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Base/Move.py", line 468, in get_game_move
    ok, mens_error = position.play(from_sq, to_sq, promotion)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Base/Position.py", line 254, in play
    enr_k = mv.iscastle_k()
            ^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'iscastle_k'
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer
2025-09-01 11:48:17.844775
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/LucasR.py", line 25, in <module>
    Code.Base.Init.init()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Base/Init.py", line 18, in init
    resp = LucasChessGui.run_gui(main_procesador)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/LucasChessGui.py", line 133, in run_gui
    procesador.iniciar_gui()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 184, in iniciar_gui
    self.main_window = MainWindow.MainWindow(self)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/MainWindow.py", line 31, in __init__
    self.base = WBase.WBase(self, manager)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/WBase.py", line 87, in __init__
    self.create_toolbar()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/WBase.py", line 136, in create_toolbar
    if Code.eboard:
       ^^^^
UnboundLocalError: cannot access local variable 'Code' where it is not associated with a value
2025-09-01 11:48:30.691492
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/LucasR.py", line 25, in <module>
    Code.Base.Init.init()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Base/Init.py", line 18, in init
    resp = LucasChessGui.run_gui(main_procesador)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/LucasChessGui.py", line 133, in run_gui
    procesador.iniciar_gui()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 184, in iniciar_gui
    self.main_window = MainWindow.MainWindow(self)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/MainWindow.py", line 31, in __init__
    self.base = WBase.WBase(self, manager)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/WBase.py", line 87, in __init__
    self.create_toolbar()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/WBase.py", line 136, in create_toolbar
    if Code.eboard:
       ^^^^
UnboundLocalError: cannot access local variable 'Code' where it is not associated with a value
2025-09-01 11:49:11.306668
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/LucasR.py", line 25, in <module>
    Code.Base.Init.init()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Base/Init.py", line 18, in init
    resp = LucasChessGui.run_gui(main_procesador)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/LucasChessGui.py", line 133, in run_gui
    procesador.iniciar_gui()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 184, in iniciar_gui
    self.main_window = MainWindow.MainWindow(self)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/MainWindow.py", line 31, in __init__
    self.base = WBase.WBase(self, manager)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/WBase.py", line 87, in __init__
    self.create_toolbar()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/WBase.py", line 136, in create_toolbar
    if Code.eboard:
       ^^^^
UnboundLocalError: cannot access local variable 'Code' where it is not associated with a value
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer
2025-09-01 12:48:36.153496
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/BoardElements.py", line 348, in mouseReleaseEvent
    self.board.try_to_move(self, event.scenePos(), event.button())
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/Board.py", line 1871, in try_to_move
    if not self.mensajero(from_sq, to_sq):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Manager.py", line 2382, in player_has_moved_base
    return self.messenger(from_sq, to_sq, promotion)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/PlayAgainstEngine/ManagerPlayAgainstEngine.py", line 1453, in player_has_moved
    if not self.tutor_book.si_esta(fen_base, a1h8):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Books/Books.py", line 317, in si_esta
    lista_jugadas = self.get_list_moves(fen)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Books/Books.py", line 166, in get_list_moves
    li = self.book.lista(self.path, fen)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Books/Polyglot.py", line 125, in lista
    return self.xlista(fen)
           ^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Books/Polyglot.py", line 128, in xlista
    key = self.hash(fen)
          ^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Books/Polyglot.py", line 61, in hash
    return FasterCode.hash_polyglot8(fen)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'FasterCode' has no attribute 'hash_polyglot8'
2025-09-01 12:53:44.379590
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/BoardElements.py", line 348, in mouseReleaseEvent
    self.board.try_to_move(self, event.scenePos(), event.button())
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/Board.py", line 1871, in try_to_move
    if not self.mensajero(from_sq, to_sq):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Manager.py", line 2382, in player_has_moved_base
    return self.messenger(from_sq, to_sq, promotion)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/GM/ManagerGM.py", line 315, in player_has_moved
    desde_gm, hasta_gm, promotion_gm = WindowGM.select_move(self, li_moves, True)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/GM/WindowGM.py", line 585, in select_move
    from_sq, to_sq, promotion, label, pgn = li_moves[0]
                                            ~~~~~~~~^^^
IndexError: list index out of range
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer
2025-09-01 16:47:05.067701
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/BoardElements.py", line 545, in mousePressEvent
    self.rutina()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/Board.py", line 995, in launch_visual_menu
    self.cambiaPiezas(resp)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/Board.py", line 1080, in cambiaPiezas
    Code.all_pieces.save_all_png(nom_pieces_ori, 30)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/QT/Piezas.py", line 128, in save_all_png
    fich = Code.path_resource("Pieces", name, "%s%s.svg" % (color, pieza))
           ^^^^
UnboundLocalError: cannot access local variable 'Code' where it is not associated with a value
2025-09-01 16:47:14.799304
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/BoardElements.py", line 545, in mousePressEvent
    self.rutina()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/Board.py", line 995, in launch_visual_menu
    self.cambiaPiezas(resp)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/Board.py", line 1080, in cambiaPiezas
    Code.all_pieces.save_all_png(nom_pieces_ori, 30)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/QT/Piezas.py", line 128, in save_all_png
    fich = Code.path_resource("Pieces", name, "%s%s.svg" % (color, pieza))
           ^^^^
UnboundLocalError: cannot access local variable 'Code' where it is not associated with a value
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer
2025-09-01 16:49:54.512833
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/BoardElements.py", line 545, in mousePressEvent
    self.rutina()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/Board.py", line 1016, in launch_visual_menu
    self.cambiaPiezas(nom_pieces_ori)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/Board.py", line 1080, in cambiaPiezas
    Code.all_pieces.save_all_png(nom_pieces_ori, 30)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/QT/Piezas.py", line 128, in save_all_png
    fich = Code.path_resource("Pieces", name, "%s%s.svg" % (color, pieza))
           ^^^^
UnboundLocalError: cannot access local variable 'Code' where it is not associated with a value
2025-09-01 16:49:58.841498
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/BoardElements.py", line 545, in mousePressEvent
    self.rutina()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/Board.py", line 1016, in launch_visual_menu
    self.cambiaPiezas(nom_pieces_ori)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/Board.py", line 1080, in cambiaPiezas
    Code.all_pieces.save_all_png(nom_pieces_ori, 30)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/QT/Piezas.py", line 128, in save_all_png
    fich = Code.path_resource("Pieces", name, "%s%s.svg" % (color, pieza))
           ^^^^
UnboundLocalError: cannot access local variable 'Code' where it is not associated with a value
2025-09-01 16:50:02.365331
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/BoardElements.py", line 545, in mousePressEvent
    self.rutina()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/Board.py", line 1016, in launch_visual_menu
    self.cambiaPiezas(nom_pieces_ori)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/Board.py", line 1080, in cambiaPiezas
    Code.all_pieces.save_all_png(nom_pieces_ori, 30)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/QT/Piezas.py", line 128, in save_all_png
    fich = Code.path_resource("Pieces", name, "%s%s.svg" % (color, pieza))
           ^^^^
UnboundLocalError: cannot access local variable 'Code' where it is not associated with a value
2025-09-01 16:50:07.326114
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/BoardElements.py", line 545, in mousePressEvent
    self.rutina()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/Board.py", line 998, in launch_visual_menu
    self.cambiaSize()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/Board.py", line 1055, in cambiaSize
    imp = WTamBoard(self)
          ^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/Board.py", line 2660, in __init__
    self.setWindowFlags(QtCore.Qt.WindowCloseButtonHint | QtCore.Qt.Dialog | QtCore.Qt.WindowTitleHint)
TypeError: 'PySide2.QtCore.Qt.WindowType' object cannot be interpreted as an integer
2025-09-01 16:50:18.463574
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/BoardElements.py", line 545, in mousePressEvent
    self.rutina()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/Board.py", line 1016, in launch_visual_menu
    self.cambiaPiezas(nom_pieces_ori)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/Board.py", line 1080, in cambiaPiezas
    Code.all_pieces.save_all_png(nom_pieces_ori, 30)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/QT/Piezas.py", line 128, in save_all_png
    fich = Code.path_resource("Pieces", name, "%s%s.svg" % (color, pieza))
           ^^^^
UnboundLocalError: cannot access local variable 'Code' where it is not associated with a value
2025-09-01 16:50:21.992849
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/BoardElements.py", line 545, in mousePressEvent
    self.rutina()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/Board.py", line 998, in launch_visual_menu
    self.cambiaSize()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/Board.py", line 1055, in cambiaSize
    imp = WTamBoard(self)
          ^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/Board.py", line 2660, in __init__
    self.setWindowFlags(QtCore.Qt.WindowCloseButtonHint | QtCore.Qt.Dialog | QtCore.Qt.WindowTitleHint)
TypeError: 'PySide2.QtCore.Qt.WindowType' object cannot be interpreted as an integer
2025-09-01 16:50:50.013042
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/BoardElements.py", line 545, in mousePressEvent
    self.rutina()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/Board.py", line 998, in launch_visual_menu
    self.cambiaSize()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/Board.py", line 1055, in cambiaSize
    imp = WTamBoard(self)
          ^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/Board.py", line 2660, in __init__
    self.setWindowFlags(QtCore.Qt.WindowCloseButtonHint | QtCore.Qt.Dialog | QtCore.Qt.WindowTitleHint)
TypeError: 'PySide2.QtCore.Qt.WindowType' object cannot be interpreted as an integer
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer
2025-09-01 17:00:21.126234
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/BoardElements.py", line 545, in mousePressEvent
    self.rutina()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/Board.py", line 998, in launch_visual_menu
    self.cambiaSize()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/Board.py", line 1055, in cambiaSize
    imp = WTamBoard(self)
          ^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/Board.py", line 2660, in __init__
    self.setWindowFlags(QtCore.Qt.WindowCloseButtonHint | QtCore.Qt.Dialog | QtCore.Qt.WindowTitleHint)
TypeError: 'PySide2.QtCore.Qt.WindowType' object cannot be interpreted as an integer
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer
2025-09-01 17:03:08.985384
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/LucasR.py", line 25, in <module>
    Code.Base.Init.init()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Base/Init.py", line 18, in init
    resp = LucasChessGui.run_gui(main_procesador)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/LucasChessGui.py", line 133, in run_gui
    procesador.iniciar_gui()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 220, in iniciar_gui
    self.start()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 255, in start
    self.cambiaconfigurationPrimeraVez()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 777, in cambiaconfigurationPrimeraVez
    if WindowConfig.options_first_time(self.main_window, self.configuration):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Config/WindowConfig.py", line 354, in options_first_time
    result = QTUtil2.read_simple(parent, _("Player"), _("Player's name"), configuration.x_player)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/QT/QTUtil2.py", line 861, in read_simple
    v = SimpleWindow(owner, title, label, value, mas_info, width, in_cursor, li_values)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/QT/QTUtil2.py", line 817, in __init__
    self.setWindowFlags(QtCore.Qt.WindowCloseButtonHint | QtCore.Qt.Dialog | QtCore.Qt.WindowTitleHint)
TypeError: 'PySide2.QtCore.Qt.WindowType' object cannot be interpreted as an integer
2025-09-01 17:03:14.455671
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/LucasR.py", line 25, in <module>
    Code.Base.Init.init()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Base/Init.py", line 18, in init
    resp = LucasChessGui.run_gui(main_procesador)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/MainWindow/LucasChessGui.py", line 133, in run_gui
    procesador.iniciar_gui()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 220, in iniciar_gui
    self.start()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 255, in start
    self.cambiaconfigurationPrimeraVez()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Procesador.py", line 777, in cambiaconfigurationPrimeraVez
    if WindowConfig.options_first_time(self.main_window, self.configuration):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Config/WindowConfig.py", line 354, in options_first_time
    result = QTUtil2.read_simple(parent, _("Player"), _("Player's name"), configuration.x_player)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/QT/QTUtil2.py", line 861, in read_simple
    v = SimpleWindow(owner, title, label, value, mas_info, width, in_cursor, li_values)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/QT/QTUtil2.py", line 817, in __init__
    self.setWindowFlags(QtCore.Qt.WindowCloseButtonHint | QtCore.Qt.Dialog | QtCore.Qt.WindowTitleHint)
TypeError: 'PySide2.QtCore.Qt.WindowType' object cannot be interpreted as an integer
2025-09-01 17:03:44.583853
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/BoardElements.py", line 545, in mousePressEvent
    self.rutina()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/Board.py", line 998, in launch_visual_menu
    self.cambiaSize()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/Board.py", line 1055, in cambiaSize
    imp = WTamBoard(self)
          ^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/Board.py", line 2660, in __init__
    self.setWindowFlags(QtCore.Qt.WindowCloseButtonHint | QtCore.Qt.Dialog | QtCore.Qt.WindowTitleHint)
TypeError: 'PySide2.QtCore.Qt.WindowType' object cannot be interpreted as an integer
2025-09-01 17:04:02.442700
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/BoardElements.py", line 545, in mousePressEvent
    self.rutina()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/Board.py", line 1016, in launch_visual_menu
    self.cambiaPiezas(nom_pieces_ori)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/Board.py", line 1080, in cambiaPiezas
    Code.all_pieces.save_all_png(nom_pieces_ori, 30)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/QT/Piezas.py", line 128, in save_all_png
    fich = Code.path_resource("Pieces", name, "%s%s.svg" % (color, pieza))
           ^^^^
UnboundLocalError: cannot access local variable 'Code' where it is not associated with a value
2025-09-01 17:04:17.005666
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/BoardElements.py", line 545, in mousePressEvent
    self.rutina()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/Board.py", line 1016, in launch_visual_menu
    self.cambiaPiezas(nom_pieces_ori)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/Board.py", line 1080, in cambiaPiezas
    Code.all_pieces.save_all_png(nom_pieces_ori, 30)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/QT/Piezas.py", line 128, in save_all_png
    fich = Code.path_resource("Pieces", name, "%s%s.svg" % (color, pieza))
           ^^^^
UnboundLocalError: cannot access local variable 'Code' where it is not associated with a value
2025-09-01 17:04:22.151364
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/BoardElements.py", line 545, in mousePressEvent
    self.rutina()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/Board.py", line 1016, in launch_visual_menu
    self.cambiaPiezas(nom_pieces_ori)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/Board.py", line 1080, in cambiaPiezas
    Code.all_pieces.save_all_png(nom_pieces_ori, 30)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/QT/Piezas.py", line 128, in save_all_png
    fich = Code.path_resource("Pieces", name, "%s%s.svg" % (color, pieza))
           ^^^^
UnboundLocalError: cannot access local variable 'Code' where it is not associated with a value
2025-09-01 17:04:27.308301
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/BoardElements.py", line 545, in mousePressEvent
    self.rutina()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/Board.py", line 998, in launch_visual_menu
    self.cambiaSize()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/Board.py", line 1055, in cambiaSize
    imp = WTamBoard(self)
          ^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/Board.py", line 2660, in __init__
    self.setWindowFlags(QtCore.Qt.WindowCloseButtonHint | QtCore.Qt.Dialog | QtCore.Qt.WindowTitleHint)
TypeError: 'PySide2.QtCore.Qt.WindowType' object cannot be interpreted as an integer
2025-09-01 17:04:36.499999
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/BoardElements.py", line 545, in mousePressEvent
    self.rutina()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/Board.py", line 1016, in launch_visual_menu
    self.cambiaPiezas(nom_pieces_ori)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/Board.py", line 1080, in cambiaPiezas
    Code.all_pieces.save_all_png(nom_pieces_ori, 30)
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/QT/Piezas.py", line 128, in save_all_png
    fich = Code.path_resource("Pieces", name, "%s%s.svg" % (color, pieza))
           ^^^^
UnboundLocalError: cannot access local variable 'Code' where it is not associated with a value
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer
TypeError: 'PySide2.QtCore.Qt.AlignmentFlag' object cannot be interpreted as an integer
2025-09-01 22:29:51.639691
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/BoardElements.py", line 545, in mousePressEvent
    self.rutina()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/Board.py", line 998, in launch_visual_menu
    self.cambiaSize()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/Board.py", line 1055, in cambiaSize
    imp = WTamBoard(self)
          ^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/Board.py", line 2660, in __init__
    self.setWindowFlags(QtCore.Qt.WindowCloseButtonHint | QtCore.Qt.Dialog | QtCore.Qt.WindowTitleHint)
TypeError: 'PySide2.QtCore.Qt.WindowType' object cannot be interpreted as an integer
2025-09-01 22:29:58.672881
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/BoardElements.py", line 545, in mousePressEvent
    self.rutina()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/Board.py", line 998, in launch_visual_menu
    self.cambiaSize()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/Board.py", line 1055, in cambiaSize
    imp = WTamBoard(self)
          ^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/Board.py", line 2660, in __init__
    self.setWindowFlags(QtCore.Qt.WindowCloseButtonHint | QtCore.Qt.Dialog | QtCore.Qt.WindowTitleHint)
TypeError: 'PySide2.QtCore.Qt.WindowType' object cannot be interpreted as an integer
2025-09-01 22:31:52.317676
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/BoardElements.py", line 545, in mousePressEvent
    self.rutina()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/Board.py", line 1003, in launch_visual_menu
    self.cambiaSize()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/Board.py", line 1060, in cambiaSize
    imp = WTamBoard(self)
          ^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/Board.py", line 2665, in __init__
    self.setWindowFlags(QtCore.Qt.WindowCloseButtonHint | QtCore.Qt.Dialog | QtCore.Qt.WindowTitleHint)
TypeError: 'PySide2.QtCore.Qt.WindowType' object cannot be interpreted as an integer
2025-09-01 22:33:27.458976
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/BoardElements.py", line 545, in mousePressEvent
    self.rutina()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/Board.py", line 1004, in launch_visual_menu
    self.cambiaSize()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/Board.py", line 1061, in cambiaSize
    imp = WTamBoard(self)
          ^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/Board.py", line 2666, in __init__
    self.setWindowFlags(QtCore.Qt.WindowCloseButtonHint | QtCore.Qt.Dialog | QtCore.Qt.WindowTitleHint)
TypeError: 'PySide2.QtCore.Qt.WindowType' object cannot be interpreted as an integer
2025-09-01 22:38:37.604507
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/BoardElements.py", line 545, in mousePressEvent
    self.rutina()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/Board.py", line 1015, in launch_visual_menu
    self.cambiaSize()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/Board.py", line 1120, in cambiaSize
    self.config_board.setWidthPiece(new_size)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigBoard' object has no attribute 'setWidthPiece'
2025-09-01 22:42:25.965127
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/BoardElements.py", line 545, in mousePressEvent
    self.rutina()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/Board.py", line 1015, in launch_visual_menu
    self.cambiaSize()
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/Board.py", line 1075, in cambiaSize
    imp = WTamBoard(self)
          ^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/Board.py", line 2683, in __init__
    self.setWindowFlags(QtCore.Qt.WindowCloseButtonHint | QtCore.Qt.Dialog | QtCore.Qt.WindowTitleHint)
TypeError: 'PySide2.QtCore.Qt.WindowType' object cannot be interpreted as an integer
2025-09-01 22:43:52.155134
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/Board.py", line 2694, in __init__
    self.setWindowFlags(QtCore.Qt.WindowCloseButtonHint | QtCore.Qt.Dialog | QtCore.Qt.WindowTitleHint)
TypeError: 'PySide2.QtCore.Qt.WindowType' object cannot be interpreted as an integer
2025-09-01 22:43:52.262985
Traceback (most recent call last):
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/Board.py", line 1076, in cambiaSize
    imp = WTamBoard(self)
          ^^^^^^^^^^^^^^^
  File "/Volumes/Mini-Ext/mini-external/Development/Lucas/lucaschessR2/bin/Code/Board/Board.py", line 2694, in __init__
    self.setWindowFlags(QtCore.Qt.WindowCloseButtonHint | QtCore.Qt.Dialog | QtCore.Qt.WindowTitleHint)
TypeError: 'PySide2.QtCore.Qt.WindowType' object cannot be interpreted as an integer
